# #7 Python set path in windows and help()

In [2]:
print("Hello World!")

Hello World!


In [3]:
help()

Welcome to Python 3.12's help utility! If this is your first time using
Python, you should definitely check out the tutorial at
https://docs.python.org/3.12/tutorial/.

Enter the name of any module, keyword, or topic to get help on writing
Python programs and using Python modules.  To get a list of available
modules, keywords, symbols, or topics, enter "modules", "keywords",
"symbols", or "topics".

Each module also comes with a one-line summary of what it does; to list
the modules whose name or summary contain a given string such as "spam",
enter "modules spam".

To quit this help utility and return to the interpreter,
enter "q" or "quit".


Here is a list of available topics.  Enter any topic name to get more help.

ASSERTION           DELETION            LOOPING             SHIFTING
ASSIGNMENT          DICTIONARIES        MAPPINGMETHODS      SLICINGS
ATTRIBUTEMETHODS    DICTIONARYLITERALS  MAPPINGS            SPECIALATTRIBUTES
ATTRIBUTES          DYNAMICFEATURES     METHODS         

In [4]:
# to find help for specific topic
help("LISTS")

Mutable Sequence Types
**********************

The operations in the following table are defined on mutable sequence
types. The "collections.abc.MutableSequence" ABC is provided to make
it easier to correctly implement these operations on custom sequence
types.

In the table *s* is an instance of a mutable sequence type, *t* is any
iterable object and *x* is an arbitrary object that meets any type and
value restrictions imposed by *s* (for example, "bytearray" only
accepts integers that meet the value restriction "0 <= x <= 255").

+--------------------------------+----------------------------------+-----------------------+
| Operation                      | Result                           | Notes                 |
|================================|==================================|=======================|
| "s[i] = x"                     | item *i* of *s* is replaced by   |                       |
|                                | *x*                              |                 

# #10 Data types in Python

In [5]:
num = 25.5
print(type(num))

<class 'float'>


In [6]:
num = 5
print(type(num))

<class 'int'>


In [7]:
num = 6 + 5j
print(type(num))

<class 'complex'>


In [8]:
# type conversion
a = 34.2
b = int(a)
print(type(b))

<class 'int'>


In [9]:
k = float(b)
print(type(k))
print(k)

<class 'float'>
34.0


In [11]:
k = 6
c = complex(b, k)
print(c)

(34+6j)


In [18]:
# boolean: True or False
bool = b < k
bool

False

In [14]:
print(type(bool))

<class 'bool'>


In [15]:
b > k

True

In [19]:
# sequence data types

lst = [23,242,112,4,132]
print(type(lst))

<class 'list'>


In [20]:
s = set(lst)

In [21]:
print(s)

{132, 4, 112, 242, 23}


In [22]:
print(type(s))

<class 'set'>


In [23]:
t = tuple(lst)

In [24]:
print(type(t))

<class 'tuple'>


In [26]:
str = "parveen"
print(str[2:6])

rvee


In [27]:
print(type(str))

<class 'str'>


In [28]:
range(0,10)

range(0, 10)

In [30]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [32]:
list(range(2,10,2))

[2, 4, 6, 8]

In [33]:
print(type(range(10)))

<class 'range'>


In [34]:
d = {
    'parveen':'samsung',
    'ajay':'apple'
}
print(d)

{'parveen': 'samsung', 'ajay': 'apple'}


In [35]:
print(d.keys())

dict_keys(['parveen', 'ajay'])


In [36]:
print(d.values())

dict_values(['samsung', 'apple'])


In [37]:
d['parveen']

'samsung'

In [38]:
d.get('ajay')

'apple'

# #17 Swap Two variables

In [54]:
r = 5
j = 2
r,j = j,r
print("R: ",r)
print("J: ",j)

R:  2
J:  5


In [55]:
t = r
r = j
j = t
print(r)
print(j)

5
2


# #18 user input

In [ ]:
a = input() #3
b = input() #2
print(a+b)

32


In [41]:
a = int(input("Enter 1st number: "))
b = int(input("Enter 2nd number: "))
print(a+b)

5


In [44]:
char = input("Enter your name: ")
print(f"Hello! {char}")

Hello! Parveen


In [ ]:
result = eval(input("enter an expr: ")) # 2+6-1
print(result)

7


# #26 Array in Python 

In [59]:
from array import *

vals = array('i', [2,12,2,31,1,1])
print(vals)


array('i', [2, 12, 2, 31, 1, 1])


In [60]:
print(vals.buffer_info())

(2056654467408, 6)


In [62]:
print(vals.typecode)

i


In [66]:
vals.reverse()

In [67]:
print(vals)

array('i', [1, 1, 31, 2, 12, 2])


In [71]:
for i in vals:
    print(i, end=" ")

1 1 31 2 12 2 

In [74]:
char = array('u',['a', 'r'])
for i in char:
    print(i)

a
r


# #27 Array values from user & search

In [75]:
from array import *

arr = array('i',[])

In [78]:
n = int(input("enter the length of the array: "))
for i in range(n):
    x = int(input("enter the next value: "))
    arr.append(x)

print(arr)

array('i', [33, 22, 33, 22, 22, 3, 2, 2, 3, 3, 2, 3, 2])


In [ ]:
k = 0
val = int(input("enter the value for search")) #33
for e in arr:
    if e==val:
        print(k)
        break

    
    k +=1
        

0


In [80]:
print(arr.index(33))

0


# #28 Numpy

In [ ]:
# pip install numpy

import numpy as np
arr = np.array([12,2,4,2,2,1])

print(arr)

[12  2  4  2  2  1]


# #31 Working with matrix

In [16]:
from numpy import *

arr1 = array([
    [1,2,4,3,2,1],
    [2,3,2,2,1,3]
])

print(arr1)

[[1 2 4 3 2 1]
 [2 3 2 2 1 3]]


In [17]:
print(arr1.dtype)

int64


In [18]:
print(arr1.ndim)

2


In [19]:
print(arr1.shape)

(2, 6)


In [20]:
print(arr1.size)

12


In [ ]:
arr2 = arr1.flatten() #multidiamensional to single  
print(arr2)

[1 2 4 3 2 1 2 3 2 2 1 3]


In [ ]:
arr3 = arr2.reshape(3,4) #one diamensional to multi diamension
print(arr3)

[[1 2 4 3]
 [2 1 2 3]
 [2 2 1 3]]


In [26]:
arr3 = arr2.reshape(2,2,3)
print(arr3)

[[[1 2 4]
  [3 2 1]]

 [[2 3 2]
  [2 1 3]]]


In [27]:
arr1 = array([
    [1,2,4,3],
    [2,3,2,2]
])

In [28]:
m = matrix(arr1)
print(m)

[[1 2 4 3]
 [2 3 2 2]]


In [29]:
print(diagonal(m))

[1 3]


In [30]:
print(m.min())

1


In [31]:
print(m.max())

4


In [35]:
m1 = matrix('1 2 3; 6 4 5; 1 6 7')
m2 = matrix('1 2 3; 6 8 7; 2 6 7')

m3 = m1 + m2

print(m3)

[[ 2  4  6]
 [12 12 12]
 [ 3 12 14]]


# #32 Functions in Python

In [36]:
def greet():
    print("Hello")
    print("Good night")

greet()

Hello
Good night


In [37]:
def add(a, b):
    return a + b

print(add(3,5))

8


# #33 Function arguments

In [ ]:
def update(x):
    x = 8
    print(x)

update(10)

8


In [42]:
def update(x):
    x = 8
    print("x: ",x)
a = 10
update(a)
print("a: ", a)

x:  8
a:  10


# #34 Types of arguments

In [ ]:
def add(a,b): #formal args
    c = a+b
    print(c)

add(5,6)

11


In [ ]:
#actual args are 4 types: position, keyword, default, variable length

def person(name, age): 
    print(name)
    print(age)

person("pravin", 23)#positonal


pravin
23


In [48]:
def person(name, age): 
    print(name)
    print(age-5)

person(age = 23,name='pravin') #keyword

pravin
18


In [52]:
def person(name, age=18): #default
    print(name)
    print(age-5)

person('pravin') 
person('pravin',45) 

pravin
13
pravin
40


In [64]:
def sum(*b): #variable length 

    print(b)
    
    c = 0
    for i in b:
        c = c + i

    print(c)

sum(3,2,34,2)

(3, 2, 34, 2)
41


# #35 Keyworded variable length

In [ ]:
def person(name, **data):
    print(name)
    print(data)

person('parveen', age=23,city='Ambala', mob=999999999)

parveen
{'age': 23, 'city': 'Ambala', 'mob': 999999999}


# #36 Global versus Local keyword

In [ ]:
a = 10 #global

def something():
    a = 16 #local
    print("in func:",a)

something()
print("outside",a)

in func: 16
outside 16


In [76]:
a = 10 #global

def something():
    global a
    a = 16 #this is now global var
    print("in func:",a)

something()
print("outside",a)

in func: 16
outside 16


# #37 Pass list to a function

In [83]:
def count(lst):
    even = 0
    odd = 0

    for i in lst:
        if i %2 ==0:
            even +=1
        else:
            odd +=1

    return even, odd


lst = [23,12,1,2,4,2,1,5,1,5,]
even,odd = count(lst)
# print(even)
# print(odd)

print("even: {} and odd: {}".format(even, odd))

even: 4 and odd: 6


# #38 Fibonacci Sequence

In [9]:
def fib(n):
    a = 0
    b = 1

    if n == 1:
        print(a)
    elif n <=0:
        print("number should be greater than 0")
    else:

        print(a)
        print(b)

        for i in range(2, n):
            c = a + b
            a = b
            b = c
            print(c)

fib(6)


0
1
1
2
3
5


# #39 Factorial 

In [10]:
def fact(n):
    f = 1

    for i in range(1, n+1):
        f *=i

    return f

x = 5
print(fact(x))



120


# #40 Recursion

In [20]:
import sys

sys.setrecursionlimit(100)
print(sys.getrecursionlimit())

100


In [ ]:

i = 0
def greet():
    global i
    i+=1

    print("hello",i)
    greet()
greet()


# #41 Factorial Using recursions


In [22]:
def fact(n):
    if n==0:
        return 1
    
    else:
       return n * fact(n - 1)

print(fact(5))


120


# #42 Anonymous Functions

In [24]:
f = lambda x,b: x*b
res = f(5,5)
print(res) 

25


# #43 Filter Map Reduce

In [1]:
def is_even(a):
    return a%2==0
        
nums = [12,24,12,42,1,34,21,24,241,241,212,]

even = list(filter(is_even,nums))
print(even)

[12, 24, 12, 42, 34, 24, 212]


In [5]:
nums = [12,24,12,42,1,34,21,24,241,241,212,]

even = list(filter(lambda n:n%2==0 ,nums))
print(even)

doubles = list(map(lambda n: n*2, nums))
print(doubles)

[12, 24, 12, 42, 34, 24, 212]
[24, 48, 24, 84, 2, 68, 42, 48, 482, 482, 424]


# #44 Decorators

In [ ]:
def div(a, b):
    if a<b:
        a,b=b,a
    return a/b

print(div(2,4))

2.0


In [14]:
#Change or modify the functionalities of existing functions using decorators

def div(a, b):
    return a/b

def smart_div(func):
    def inner(a,b):
        if a<b:
            a,b=b,a
            return func(a,b)
    return inner



div1 = smart_div(div)
div1(2,4)

2.0

# #45 Modules

In [17]:
from calc import *

a = 6
b = 2

print(add(a,b))
print(sub(a,b))
print(mul(a,b))
print(div(a,b))

8
4
12
3.0


# #46 Special Variable __name__

In [19]:
print(__name__)

__main__


In [20]:
import calc
print("Demo says : "+ __name__)

Demo says : __main__


In [21]:
import demo
print("Its time to calculate")

hello
welcome user
Its time to calculate


In [ ]:
import demo  #in demo.py: if __name__ == "__main__":
print("Its time to calculate")

Its time to calculate


# #47 Special Variable __name__ part 2

In [ ]:
def add():
    # return a+b
    print("result 1 is ")
def sub():
    # return a-b
    print("result 2 is")

def main():
    add()
    sub()

if __name__ == "__main__":
    main()

In [ ]:
# demo.py

from calc import add

def fun1():
    add()
    print('from fun1')

def fun2():
    print('from fun2')

def main():

    fun1()
    fun2() 

main()

# #48 Object Oriented Programming

In [ ]:
'''pyhton supports all diff programming paradigms including procedural, functional or object oriented programming.
1. procedural oriented programming: Writing code in procedures (functions), breaking problems into smaller reusable parts.
2. functional programmming: Using pure functions without side effects, passing functions as arguments, returning functions, using concepts like map, filter, reduce, and recursion.
'''

'''OOPS: try to solve a real world issue with the help of virtual world solution
object: any real world entity is obj. Each obj have two properties 1. attribute(variable) 2. behaviour(methods)
functions in oops are called methods
class: design of objects or methods etc

in simple: class = desing, blueprint and object = instance
'''

'OOPS: try to solve a real world issue with the help of virtual world solution\nobject: any real world entity is obj. Each obj have two attribute 1. property 2. behaviour\nfunctions in oops are called methods\nclass: design of objects or methods etc\n\nin simple: class = desing, blueprint and object = instance\n'

# #49 Class and Object

In [ ]:
class computer:
    def config(self):
        print("i5, 16GB, 1TB")


x = 9
print(type(x))
a = '5'
print(type(a))
com1 = computer()

print(type(com1))

# everything in python is a object there are some inbuilt objects and some we create using class.
    

<class 'int'>
<class 'str'>
<class '__main__.computer'>


In [ ]:
class computer:
    def config(self):
        print("i5, 16GB, 1TB")


x = 9
a = '5'
com1 = computer()
computer.config(com1)

i5, 16GB, 1TB


In [32]:
class computer:
    def config(self):
        print("i5, 16GB, 1TB")


x = 9
a = '5'
com1 = computer()
com2 = computer()


computer.config(com1)
computer.config(com2)

com1.config()
com2.config()

i5, 16GB, 1TB
i5, 16GB, 1TB
i5, 16GB, 1TB
i5, 16GB, 1TB


# #50  __init__ method

In [ ]:
class computer:
    def __init__(self):
        print("In init") #automatically called for each object


    def config(self):
        print("i5, 16GB, 1TB")

com1 = computer()
com2 = computer()

com1.config()
com2.config()

In init
In init
i5, 16GB, 1TB
i5, 16GB, 1TB


In [35]:
class computer:
    def __init__(self, cpu, ram):
        self.cpu = cpu
        self.ram = ram


    def config(self):
        print("Config is: ", self.cpu, self.ram)

com1 = computer('i3', 16)
com2 = computer('ryzen 5', 8)

com1.config()
com2.config()

Config is:  i3 16
Config is:  ryzen 5 8


# #51 Constructor, Self and Comparing Objects

In [38]:
class computer:
    pass


c1 = computer()
c2 = computer()
print(id(c1))
print(id(c2))

1338675820400
1338676657232


In [45]:
class computer:
    def __init__(self):
        self.name = "pravin"
        self.age = 23
    
    def update(self):
        self.age = 22

c1 = computer()
c2 = computer()

c1.name = "John"
c1.age = 20
c1.update()
print(c1.name, c1.age)
print(c2.name, c2.age)

John 22
pravin 23


In [55]:
class computer:
    def __init__(self):
        self.name = "pravin"
        self.age = 23
    
    def compare(self, other):
        return self.age == other.age
        
c1 = computer()
c2 = computer()

c1.age = 45

if c1.compare(c2):
    print("They are same")
else:
    print("They are different")

print(c1.name, c1.age)
print(c2.name, c2.age)

They are different
pravin 45
pravin 23


# #52 Types of Variables 

In [58]:
class car:
    def __init__(self):
        self.mil = 20
        self.com = "bmw"

c1=car()
c2=car()

c1.mil = 12

print(c1.com, c1.mil)
print(c2.com, c2.mil)
    

bmw 12
bmw 20


In [66]:
class car:

    wheels = 4 #class namespace (variable)

    def __init__(self):
        self.mil = 20
        self.com = "bmw" #instance namespace(variable)

c1=car()
c2=car()

c1.mil = 12

print(c1.com, c1.mil, c1.wheels)
print(c2.com, c2.mil, c2.wheels)

#namespace - namespace is an area where you create and store object/variable

bmw 12 4
bmw 20 4


In [177]:
class car:

    wheels = 4 #class namespace

    def __init__(self):
        self.mil = 20
        self.com = "bmw" #instance namespace

c1=car()
c2=car()

c1.mil = 12
car.wheels = 5

print(c1.com, c1.mil, c1.wheels)
print(c2.com, c2.mil, c2.wheels)


bmw 12 5
bmw 20 5


# #53 Types of Methods

In [ ]:
'''
variable to store data
method to control behaviour

'''

In [3]:
class student:

    school = 'dL-uNI'

    def __init__(self, m1, m2, m3):
        self.m1 = m1
        self.m2 = m2
        self.m3 = m3

    def avg(self): #instance method as it works with the object
        return (self.m1 + self.m2+self.m3)/3

s1 = student(34,45,23)
s2 = student(45,45,26)


print(s1.avg())
print(s2.avg())

34.0
38.666666666666664


In [7]:
class student:

    school = 'dL-uNI'

    def __init__(self, m1, m2, m3):
        self.m1 = m1
        self.m2 = m2
        self.m3 = m3

    def avg(self): #instance method as it works with the object
        return (self.m1 + self.m2+self.m3)/3
    
    def get_m1(self): #accessors 
        return self.m1
    
    def set_m1(self): #mutators
        self.m1 = 23
        return self.m1

s1 = student(34,45,23)
s2 = student(45,45,26)

print(s1.get_m1())
print(s1.set_m1())


print(s1.avg())
print(s2.avg())

34
23
30.333333333333332
38.666666666666664


In [12]:
class student:

    school = 'dL-uNI'

    def __init__(self, m1, m2, m3):
        self.m1 = m1
        self.m2 = m2
        self.m3 = m3

    def avg(self):
        return (self.m1 + self.m2+self.m3)/3
    
    @classmethod
    def info(cls): #class method
        return cls.school

s1 = student(34,45,23)
s2 = student(45,45,26)

print(student.info())

dL-uNI


In [14]:
class student:

    school = 'dL-uNI'

    def __init__(self, m1, m2, m3):
        self.m1 = m1
        self.m2 = m2
        self.m3 = m3

    def avg(self):
        return (self.m1 + self.m2+self.m3)/3
    
    @classmethod
    def getSchool(cls): #class method
        return cls.school
    
    @staticmethod
    def info(): #static method
        print("THis is student class")

s1 = student(34,45,23)
s2 = student(45,45,26)

print(student.getSchool())

student.info()

dL-uNI
THis is student class


# #54 Inner class

In [15]:
class student:

    def __init__(self, name, rollno):
        self.name = name
        self.rollno = rollno

s1 = student('pravin', 2)
s2 = student('jeon', 4)

print(s1.name, s1.rollno)

pravin 2


In [16]:
class student:

    def __init__(self, name, rollno):
        self.name = name
        self.rollno = rollno
    
    def show(self):
        print(self.name, self.rollno)


s1 = student('pravin', 2)
s2 = student('jeon', 4)

s1.show()

pravin 2


In [18]:
class student:

    def __init__(self, name, rollno):
        self.name = name
        self.rollno = rollno

        self.lap = self.laptop()
    
    def show(self):
        print(self.name, self.rollno)

    class laptop: # inner class 

        def __init__(self):
            self.brand = 'hp'
            self.cpu = 'ryzen 5'
            self.ram = 8

        def show(self):
            print(self.brand, self.cpu, self.ram )


s1 = student('pravin', 2)
s2 = student('jeon', 4)

s1.show()

lap1 = s1.lap
lap2 = s2.lap

print(lap1.cpu)

print(id(lap2))


pravin 2
ryzen 5
1430883954960


In [22]:
class student:

    def __init__(self, name, rollno):
        self.name = name
        self.rollno = rollno

        self.lap = self.laptop()
    
    def show(self):
        print(self.name, self.rollno)
        self.lap.show()

    class laptop: # inner class 

        def __init__(self):
            self.brand = 'hp'
            self.cpu = 'ryzen 5'
            self.ram = 8

        def show(self):
            print(self.brand, self.cpu, self.ram )


s1 = student('pravin', 2)
s2 = student('jeon', 4)

s1.show()

pravin 2
hp ryzen 5 8


# #55 Inheritance

In [28]:
class a: #superclass
    def feature1(self):
        print("feature 1 working")
    
    def feature2(self):
        print("feature 2 working")

class b(a): #b is inheriting the object of class a, b is Subclass, this is single level inheritance
    def feature3(self):
        print("feature 3 working")
    
    def feature4(self):
        print("feature 4 working")

class c(b): #this is multilevel inheritance
    def feature5(self):
        print("feature 5 working")


a1 = a()
a1.feature1()
a1.feature2()

b1 = b()
b1.feature3()

c1=c()
c1.f



feature 1 working
feature 2 working
feature 3 working


In [31]:
class a: #superclass
    def feature1(self):
        print("feature 1 working")
    
    def feature2(self):
        print("feature 2 working")

class b: #superclass
    def feature3(self):
        print("feature 3 working")
    
    def feature4(self):
        print("feature 4 working")

class c(b,a): #this is multiple inheritance
    def feature5(self):
        print("feature 5 working")

c1=c()
c1.feature2()
c1.feature4()



feature 2 working
feature 4 working


# #56  Constructor in Inheritance

In [34]:
class a: 

    def __init__(self):
        print("In a init")

    def feature1(self):
        print("feature 1 working")
    
    def feature2(self):
        print("feature 2 working")

class b(a): 
    def feature3(self):
        print("feature 3 working")
    
    def feature4(self):
        print("feature 4 working")


a1 = b()

In a init


In [35]:
class a: 

    def __init__(self):
        print("In a init")

    def feature1(self):
        print("feature 1 working")
    
    def feature2(self):
        print("feature 2 working")

class b(a): 
    
    def __init__(self):
        print("In b init")


    def feature3(self):
        print("feature 3 working")
    
    def feature4(self):
        print("feature 4 working")


a1 = b()

In b init


In [37]:
'''to call the init of both the classes 
by default it is calling the b init if present or if not then init of a class but when both init are there it is only calling the init of b
in order to this to access all the features of superclass including the init there is the method called super()'''
class a: 

    def __init__(self):
        print("In a init")

    def feature1(self):
        print("feature 1 working")
    
    def feature2(self):
        print("feature 2 working")

class b(a): 

    def __init__(self):
        print("In b init")
        super().__init__() #to access all the methods or object of superclass 

    def feature3(self):
        print("feature 3 working")
    
    def feature4(self):
        print("feature 4 working")


a1 = b()

In b init
In a init


In [45]:
class a: 

    def __init__(self):
        print("In a init")

    def feature1(self):
        print("feature 1 working")
    
    def feature2(self):
        print("feature 2 working")

class b: 

    def __init__(self):
        print("In b init")

    def feature3(self):
        print("feature 3 working")
    
    def feature4(self):
        print("feature 4 working")

class c(a,b):
    def __init__(self):
        print("In c init")

        super().__init__() #why not b: Method resolution order: left to right


    def feat(self):
        super().feature3()

a1 = c()
a1.feat()

In c init
In a init
feature 3 working


# #57 Introduction to Polymorphism

In [ ]:
'''Poly - many, morph - form
    One thing can take multiple forms'''

# #58 Duck Typing

In [50]:
'''duck test: if it looks like a duck, swims like a duck, and quacks like a duck, then it probably is a duck.'''

# x = 5
# x = 'pravin'


class pycharm:
    def execute(self):
        print("compiling")
        print("running")

class laptop:
    def code(self, ide):
        ide.execute()


ide = pycharm()


lap1 = laptop()
lap1.code(ide)


compiling
running


In [52]:
class pycharm:
    def execute(self):
        print("compiling")
        print("running")

class myide:

    def execute(self):
        print("spell check ")
        print("convention check")
        print("compiling")
        print("running")

class laptop:
    def code(self, ide):
        ide.execute()


ide = myide()


lap1 = laptop()
lap1.code(ide)


spell check 
convention check
compiling
running


# #59 Operator Overloading | Polymorphism

In [59]:
# a = 5
# b = 6
# print(a+b)

# int.__add__(a,b)


class student:
    def __init__(self, m1, m2):
        self.m1 = m1
        self.m2 = m2

    def __add__(self, other):
        m1 = self.m1 + other.m1
        m2 = self.m2 + other.m2

        s3 = student(m1, m2)
        return s3
s1 = student(56, 23)
s2 = student(66, 22)

s3 = s1+s2
print(s3.m1)
        

122


# #60 Method Overloading and Method Overriding

In [66]:
'''
Method overloading : two method with the same name but different parameters or args,python doesn't support method overloading directly
Method overriding : two methods wiht the same name and same number of parametes or args
'''

class student:

    def __init__(self, m1, m2):
        self.m1 = m1
        self.m2 = m2
        
    def sum(self, a=None, b=None, c=None):

        s = 0
        if a!=None and b!=None and 
        s = a+b+c
        return s        

s1 = student(58,43)

s1.sum(5,9,23)

37

In [70]:
#method overriding
class a:
    def show(self):
        print("in A show")

class b(a):
    pass

a1 = b()
a1.show()

in A show


In [72]:
#method overriding
class a:
    def show(self):
        print("in A show")

class b(a):
    
    def show(self):
        print("In B show")

a1 = b()
a1.show()

In B show


# #61 Iterator

In [82]:
nums = [2,1,2,14,5,35,657,86]

it = iter(nums)
print(it.__next__()) 
print(it.__next__())
print(it.__next__())


2
1
2


In [90]:
class topten:
    def __init__(self):
        self.num = 1

    def __iter__(self):
        return self
    
    def __next__(self):
        if self.num <=10:
            val = self.num
            self.num +=1

            return val
        
        else:
            raise StopIteration

vals= topten()

# print(vals.__next__())
# print(vals.__next__())
for i in vals:
    print(i)



1
2
3
4
5
6
7
8
9
10


# #62 Generators

In [ ]:
def topten():

    n = 1

    while n <= 10:
        sq = n*n
        yield sq
        n +=1

values = topten()

# print(values.__next__())
# print(values.__next__())
# print(values.__next__())

for i in values:
    print(i)

# #63 Exception Handling

In [94]:
'''
errors: compile time, run time, logical
the time we get run time error the execution stops, so the point is even there is a error the execution should not stop, this is the main logic of exception handling. 
'''

a = 5
b = 2

print(a/b)

print("bye")

2.5
bye


In [98]:
a = 5
b = 0

print(a/b)

print("bye")

ZeroDivisionError: division by zero

In [99]:
a = 5
b = 0

try:
    print(a/b)
except Exception:
    print("Hey, you cannot divide a number by 0")
print("bye")

Hey, you cannot divide a number by 0
bye


In [100]:
a = 5
b = 2

try:
    print(a/b)
except Exception:
    print("Hey, you cannot divide a number by 0")
print("bye")

2.5
bye


In [102]:
a = 5
b = 0

try:
    print(a/b)
except Exception as e:
    print("Hey, you cannot divide a number by 0: ",e)
print("bye")

Hey, you cannot divide a number by 0:  division by zero
bye


In [109]:
a = 5
b = 0

try:
    print("resourse open")
    print(a/b)
except Exception as e:
    print("Hey, you cannot divide a number by 0: ",e)

finally:
    print("resourse closed")

resourse open
Hey, you cannot divide a number by 0:  division by zero
resourse closed


In [115]:
a = 5
b = 0

try:
    print("resourse open")
    print(a/b)
    k = int(input("Enter a number: "))
    print(k)
except Exception as e:
    print("Hey, you cannot divide a number by 0: ",e)

finally:
    print("resourse closed")

resourse open
Hey, you cannot divide a number by 0:  division by zero
resourse closed


# #64 MultiThreading

In [ ]:
'''
Thread: lightweigth process, by default every execution has one thread'''

class hello:
    def run(self):
        for i in range(5):
            print("hello")
class hi:
    def run(self):
        for i in range(5):
            print("hi")

t1 = hello()
t2 = hi()

t1.run()
t2.run()

hello
hello
hello
hello
hello
hi
hi
hi
hi
hi


In [ ]:
from threading import *
from time import sleep
class hello:
    def run(self):
        for i in range(5):
            print("hello")
            sleep(1)
class hi:
    def run(self):
        for i in range(5):
            print("hi")
            sleep(1)

t1 = hello()
t2 = hi()

t1.run()
sleep(0.2)
t2.run()

t1.join()
t2.join()

print("bye")

# #65 File handling

In [178]:
f = open('mydata.txt', 'r')
print(f.read())


Holabenjor
Name’s ____
Into Programming & Tech
Since 19s


In [137]:
f = open('mydata.txt', 'r')
print(f.readline(), end="")
print(f.readline())

Holabenjor
Name’s ____



In [141]:
f1 = open('abc.txt', 'w') #w: write

f1.write("something")
f1.write("people")


6

In [143]:
f1 = open('abc.txt', 'a') #a: append

f1.write("add more data")

13

In [144]:
for data in f:
    print(data)

Into Programming & Tech

Since 19s


In [145]:
for data in f:
    f1.write(data)

In [148]:
f = open('parveen-github.png', 'rb')
f1 = open('git-qr.png', 'wb')
for i in f:
    f1.write(i)

# #66 Comments

In [153]:
#this is a comment

# #67 is Python Compiled or Interpreted Language?

In [154]:
#both
#interpreter: line by line
#source code -> compiler -> byte code -> interpreter(pvm) -> machine language
#the reason of converting source code to byte code is to achieve portability(platform independence)

# #68 Linear Search 

In [ ]:
pos = -1
def search(lst, n):
    global pos
    i = 0
    while i < len(lst):
        if lst[i] == n:
            pos = i
            return True
        i += 1
    return False

lst = [1,2,4,3,5,8]
n = 4

if search(lst, n):
    print("found at : ", pos+1)
else: 
    print("not found")


found at :  3


In [163]:
pos = -1
def search(lst, n):
    global pos
    for i in range(len(lst)):
        if lst[i] == n:
            pos = i
            return True
    return False

lst = [1, 2, 4, 3, 5, 8]
n = 4

if search(lst, n):
    print("found at : ", pos + 1)
else:
    print("not found")


found at :  3


# #69 Binary Search

In [168]:
pos = -1
def search(lst, n):
    global pos
    l = 0
    u = len(lst) - 1

    while l <= u:
        mid = (l + u) // 2
        if lst[mid] == n:
            pos = mid
            return True
        elif lst[mid] < n:
            l = mid + 1
        else:
            u = mid - 1
    return False

# list must be sorted
lst = [1, 2, 3, 4, 5, 8]  
n = 2

if search(lst, n):
    print("found at : ", pos + 1)
else: 
    print("not found")


found at :  2


# #70 Bubble Sort 

In [170]:
def sort(nums):
    for i in range(len(nums)-1, 0, -1):
        for j in range(i):
            if nums[j]>nums[j+1]:
                temp = nums[j]
                nums[j] = nums[j+1]
                nums[j+1] = temp
nums = [3,35,2,5,6,3,7,1]

sort(nums)
print(nums)

[1, 2, 3, 3, 5, 6, 7, 35]


# #71 Selection Sort  

In [172]:
def sort(nums):
    for i in range(5):
        minpos = i
        for j in range(i, 6):
            if nums[j] < nums[minpos]:
                minpos = j

        temp = nums[i]
        nums[i] = nums[minpos]
        nums[minpos] = temp

        print(nums)

nums = [5,3,8,6,7,2]

sort(nums)
print(nums)

[2, 3, 8, 6, 7, 5]
[2, 3, 8, 6, 7, 5]
[2, 3, 5, 6, 7, 8]
[2, 3, 5, 6, 7, 8]
[2, 3, 5, 6, 7, 8]
[2, 3, 5, 6, 7, 8]


# #72 Python Database Connection

In [173]:
#mysql setup

# #73 MySQL

In [ ]:
# pip install mysql-connector

import mysql.connector
mydb = mysql.connector.connect(host = "localhost", user="your_username", passwd="your_password", database = "db_name")

mycursor = mydb.cursor()
mycursor.execute("select * from student")

for i in mycomputer:
    print(i)


# #74  Git | PyCharm | GitHub

In [174]:
#done

# #75 Python GitHub Code Contribution

In [175]:
#done